# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - wildlifelicensing_django5

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  tagDate: $[ format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}.{0:mm}{0:ss}', pipeline.startTime) ]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/wildlifelicensing_django5')]

stages:
  - stage: Build
    condition: and(succeeded(), eq(variables.isMain, 'true'))
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image and Push
            inputs:
              command: buildAndPush
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                django5_latest
                django5_$(tagDate)
              containerRegistry: DockerHub
              repository: dbcawa/wildlifelicensing
              buildArguments: |
                GIT_COMMIT_HASH=$(Build.SourceVersion)
              arguments: --label com.azure.dev.image.build.sourceversion=$(Build.SourceVersion) --label org.opencontainers.image.revision=$(Build.SourceVersion)
            env:
              DOCKER_BUILDKIT: 1
          - task: Docker@2
            displayName: Dev Build image and Push
            inputs:
              command: buildAndPush
              dockerfile: "$(Build.SourcesDirectory)/dockerdev/Dockerfile"
              tags: |
                wildlifelicensing_dev_latest
                wildlifelicensing_dev_$(tagDate)
              containerRegistry: DockerHub
              repository: dbcawa/docker_app_dev
